spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Dailymelody?userSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

#aliyun:
#  oss:
#    endpoint: https://oss-cn-nanjing.aliyuncs.com
#    accessKeyId: ${ALIYUN_ACCESS_KEY_ID}
#    accessKeySecret: ${ALIYUN_ACCESS_KEY_SECRET}
#    bucketName: daily-melody